// This file is auto-generated by TanStack Router on dev/build.
// The placeholder below keeps TypeScript happy on cold start before the
// plugin has run. It will be overwritten on the first dev build.
/* eslint-disable */
// @ts-nocheck
import { createRootRoute } from "@tanstack/react-router";
const rootRoute = createRootRoute();
export const routeTree = rootRoute;
export interface FileRoutesByPath {}
