/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ChooseUsernameRouteImport } from './routes/choose-username'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as BetaIndexRouteImport } from './routes/beta.index'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as BetaRound2RouteImport } from './routes/beta.round-2'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as LayoutWaitlistRouteImport } from './routes/_layout.waitlist'
import { Route as LayoutVacanciesRouteImport } from './routes/_layout.vacancies'
import { Route as LayoutTourLabRouteImport } from './routes/_layout.tour-lab'
import { Route as LayoutToolsRouteImport } from './routes/_layout.tools'
import { Route as LayoutTheBarRouteImport } from './routes/_layout.the-bar'
import { Route as LayoutResourcesRouteImport } from './routes/_layout.resources'
import { Route as LayoutPlaybookRouteImport } from './routes/_layout.playbook'
import { Route as LayoutOpportunitiesPreviewRouteImport } from './routes/_layout.opportunities-preview'
import { Route as LayoutOpportunitiesRouteImport } from './routes/_layout.opportunities'
import { Route as LayoutDockLabRouteImport } from './routes/_layout.dock-lab'
import { Route as LayoutDirectoryRouteImport } from './routes/_layout.directory'
import { Route as LayoutApplicationsRouteImport } from './routes/_layout.applications'
import { Route as LayoutAppRouteImport } from './routes/_layout.app'
import { Route as LayoutAdminRouteImport } from './routes/_layout.admin'
import { Route as LayoutToolsIndexRouteImport } from './routes/_layout.tools.index'
import { Route as LayoutTheBarIndexRouteImport } from './routes/_layout.the-bar.index'
import { Route as LayoutPlaybookIndexRouteImport } from './routes/_layout.playbook.index'
import { Route as LayoutDirectoryIndexRouteImport } from './routes/_layout.directory.index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout.admin.index'
import { Route as LayoutUUsernameRouteImport } from './routes/_layout.u.$username'
import { Route as LayoutToolsCvAnalyserRouteImport } from './routes/_layout.tools.cv-analyser'
import { Route as LayoutTheBarPreviewRouteImport } from './routes/_layout.the-bar.preview'
import { Route as LayoutTheBarLeaderboardRouteImport } from './routes/_layout.the-bar.leaderboard'
import { Route as LayoutTheBarHistoryRouteImport } from './routes/_layout.the-bar.history'
import { Route as LayoutTheBarBrowseRouteImport } from './routes/_layout.the-bar.browse'
import { Route as LayoutProfileEditRouteImport } from './routes/_layout.profile.edit'
import { Route as LayoutPlaybookSlugRouteImport } from './routes/_layout.playbook.$slug'
import { Route as LayoutAdminWaitlistRouteImport } from './routes/_layout.admin.waitlist'
import { Route as LayoutAdminVacanciesRouteImport } from './routes/_layout.admin.vacancies'
import { Route as LayoutAdminOpportunitiesRouteImport } from './routes/_layout.admin.opportunities'
import { Route as LayoutAdminInsightsRouteImport } from './routes/_layout.admin.insights'
import { Route as LayoutAdminFirmSuggestionsRouteImport } from './routes/_layout.admin.firm-suggestions'
import { Route as LayoutAdminBroadcastsRouteImport } from './routes/_layout.admin.broadcasts'
import { Route as LayoutAdminBetaRouteImport } from './routes/_layout.admin.beta'
import { Route as LayoutAdminBarRouteImport } from './routes/_layout.admin.bar'
import { Route as LayoutAdminAdminsRouteImport } from './routes/_layout.admin.admins'
import { Route as LayoutTheBarChallengeIdRouteImport } from './routes/_layout.the-bar.challenge.$id'
import { Route as LayoutDirectoryFirmSlugRouteImport } from './routes/_layout.directory.firm.$slug'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseUsernameRoute = ChooseUsernameRouteImport.update({
  id: '/choose-username',
  path: '/choose-username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaIndexRoute = BetaIndexRouteImport.update({
  id: '/beta/',
  path: '/beta/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const BetaRound2Route = BetaRound2RouteImport.update({
  id: '/beta/round-2',
  path: '/beta/round-2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWaitlistRoute = LayoutWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVacanciesRoute = LayoutVacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTourLabRoute = LayoutTourLabRouteImport.update({
  id: '/tour-lab',
  path: '/tour-lab',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsRoute = LayoutToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTheBarRoute = LayoutTheBarRouteImport.update({
  id: '/the-bar',
  path: '/the-bar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResourcesRoute = LayoutResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaybookRoute = LayoutPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOpportunitiesPreviewRoute =
  LayoutOpportunitiesPreviewRouteImport.update({
    id: '/opportunities-preview',
    path: '/opportunities-preview',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutOpportunitiesRoute = LayoutOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDockLabRoute = LayoutDockLabRouteImport.update({
  id: '/dock-lab',
  path: '/dock-lab',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDirectoryRoute = LayoutDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsRoute = LayoutApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppRoute = LayoutAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsIndexRoute = LayoutToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutToolsRoute,
} as any)
const LayoutTheBarIndexRoute = LayoutTheBarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTheBarRoute,
} as any)
const LayoutPlaybookIndexRoute = LayoutPlaybookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPlaybookRoute,
} as any)
const LayoutDirectoryIndexRoute = LayoutDirectoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDirectoryRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutUUsernameRoute = LayoutUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsCvAnalyserRoute = LayoutToolsCvAnalyserRouteImport.update({
  id: '/cv-analyser',
  path: '/cv-analyser',
  getParentRoute: () => LayoutToolsRoute,
} as any)
const LayoutTheBarPreviewRoute = LayoutTheBarPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => LayoutTheBarRoute,
} as any)
const LayoutTheBarLeaderboardRoute = LayoutTheBarLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => LayoutTheBarRoute,
} as any)
const LayoutTheBarHistoryRoute = LayoutTheBarHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutTheBarRoute,
} as any)
const LayoutTheBarBrowseRoute = LayoutTheBarBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => LayoutTheBarRoute,
} as any)
const LayoutProfileEditRoute = LayoutProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaybookSlugRoute = LayoutPlaybookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutPlaybookRoute,
} as any)
const LayoutAdminWaitlistRoute = LayoutAdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminVacanciesRoute = LayoutAdminVacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminOpportunitiesRoute =
  LayoutAdminOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminInsightsRoute = LayoutAdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminFirmSuggestionsRoute =
  LayoutAdminFirmSuggestionsRouteImport.update({
    id: '/firm-suggestions',
    path: '/firm-suggestions',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminBroadcastsRoute = LayoutAdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminBetaRoute = LayoutAdminBetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminBarRoute = LayoutAdminBarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminAdminsRoute = LayoutAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutTheBarChallengeIdRoute = LayoutTheBarChallengeIdRouteImport.update({
  id: '/challenge/$id',
  path: '/challenge/$id',
  getParentRoute: () => LayoutTheBarRoute,
} as any)
const LayoutDirectoryFirmSlugRoute = LayoutDirectoryFirmSlugRouteImport.update({
  id: '/firm/$slug',
  path: '/firm/$slug',
  getParentRoute: () => LayoutDirectoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/auth': typeof AuthRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/app': typeof LayoutAppRoute
  '/applications': typeof LayoutApplicationsRoute
  '/directory': typeof LayoutDirectoryRouteWithChildren
  '/dock-lab': typeof LayoutDockLabRoute
  '/opportunities': typeof LayoutOpportunitiesRoute
  '/opportunities-preview': typeof LayoutOpportunitiesPreviewRoute
  '/playbook': typeof LayoutPlaybookRouteWithChildren
  '/resources': typeof LayoutResourcesRoute
  '/the-bar': typeof LayoutTheBarRouteWithChildren
  '/tools': typeof LayoutToolsRouteWithChildren
  '/tour-lab': typeof LayoutTourLabRoute
  '/vacancies': typeof LayoutVacanciesRoute
  '/waitlist': typeof LayoutWaitlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/beta/round-2': typeof BetaRound2Route
  '/beta/': typeof BetaIndexRoute
  '/admin/admins': typeof LayoutAdminAdminsRoute
  '/admin/bar': typeof LayoutAdminBarRoute
  '/admin/beta': typeof LayoutAdminBetaRoute
  '/admin/broadcasts': typeof LayoutAdminBroadcastsRoute
  '/admin/firm-suggestions': typeof LayoutAdminFirmSuggestionsRoute
  '/admin/insights': typeof LayoutAdminInsightsRoute
  '/admin/opportunities': typeof LayoutAdminOpportunitiesRoute
  '/admin/vacancies': typeof LayoutAdminVacanciesRoute
  '/admin/waitlist': typeof LayoutAdminWaitlistRoute
  '/playbook/$slug': typeof LayoutPlaybookSlugRoute
  '/profile/edit': typeof LayoutProfileEditRoute
  '/the-bar/browse': typeof LayoutTheBarBrowseRoute
  '/the-bar/history': typeof LayoutTheBarHistoryRoute
  '/the-bar/leaderboard': typeof LayoutTheBarLeaderboardRoute
  '/the-bar/preview': typeof LayoutTheBarPreviewRoute
  '/tools/cv-analyser': typeof LayoutToolsCvAnalyserRoute
  '/u/$username': typeof LayoutUUsernameRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/directory/': typeof LayoutDirectoryIndexRoute
  '/playbook/': typeof LayoutPlaybookIndexRoute
  '/the-bar/': typeof LayoutTheBarIndexRoute
  '/tools/': typeof LayoutToolsIndexRoute
  '/directory/firm/$slug': typeof LayoutDirectoryFirmSlugRoute
  '/the-bar/challenge/$id': typeof LayoutTheBarChallengeIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app': typeof LayoutAppRoute
  '/applications': typeof LayoutApplicationsRoute
  '/dock-lab': typeof LayoutDockLabRoute
  '/opportunities': typeof LayoutOpportunitiesRoute
  '/opportunities-preview': typeof LayoutOpportunitiesPreviewRoute
  '/resources': typeof LayoutResourcesRoute
  '/tour-lab': typeof LayoutTourLabRoute
  '/vacancies': typeof LayoutVacanciesRoute
  '/waitlist': typeof LayoutWaitlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/beta/round-2': typeof BetaRound2Route
  '/': typeof LayoutIndexRoute
  '/beta': typeof BetaIndexRoute
  '/admin/admins': typeof LayoutAdminAdminsRoute
  '/admin/bar': typeof LayoutAdminBarRoute
  '/admin/beta': typeof LayoutAdminBetaRoute
  '/admin/broadcasts': typeof LayoutAdminBroadcastsRoute
  '/admin/firm-suggestions': typeof LayoutAdminFirmSuggestionsRoute
  '/admin/insights': typeof LayoutAdminInsightsRoute
  '/admin/opportunities': typeof LayoutAdminOpportunitiesRoute
  '/admin/vacancies': typeof LayoutAdminVacanciesRoute
  '/admin/waitlist': typeof LayoutAdminWaitlistRoute
  '/playbook/$slug': typeof LayoutPlaybookSlugRoute
  '/profile/edit': typeof LayoutProfileEditRoute
  '/the-bar/browse': typeof LayoutTheBarBrowseRoute
  '/the-bar/history': typeof LayoutTheBarHistoryRoute
  '/the-bar/leaderboard': typeof LayoutTheBarLeaderboardRoute
  '/the-bar/preview': typeof LayoutTheBarPreviewRoute
  '/tools/cv-analyser': typeof LayoutToolsCvAnalyserRoute
  '/u/$username': typeof LayoutUUsernameRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/directory': typeof LayoutDirectoryIndexRoute
  '/playbook': typeof LayoutPlaybookIndexRoute
  '/the-bar': typeof LayoutTheBarIndexRoute
  '/tools': typeof LayoutToolsIndexRoute
  '/directory/firm/$slug': typeof LayoutDirectoryFirmSlugRoute
  '/the-bar/challenge/$id': typeof LayoutTheBarChallengeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/choose-username': typeof ChooseUsernameRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/app': typeof LayoutAppRoute
  '/_layout/applications': typeof LayoutApplicationsRoute
  '/_layout/directory': typeof LayoutDirectoryRouteWithChildren
  '/_layout/dock-lab': typeof LayoutDockLabRoute
  '/_layout/opportunities': typeof LayoutOpportunitiesRoute
  '/_layout/opportunities-preview': typeof LayoutOpportunitiesPreviewRoute
  '/_layout/playbook': typeof LayoutPlaybookRouteWithChildren
  '/_layout/resources': typeof LayoutResourcesRoute
  '/_layout/the-bar': typeof LayoutTheBarRouteWithChildren
  '/_layout/tools': typeof LayoutToolsRouteWithChildren
  '/_layout/tour-lab': typeof LayoutTourLabRoute
  '/_layout/vacancies': typeof LayoutVacanciesRoute
  '/_layout/waitlist': typeof LayoutWaitlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/beta/round-2': typeof BetaRound2Route
  '/_layout/': typeof LayoutIndexRoute
  '/beta/': typeof BetaIndexRoute
  '/_layout/admin/admins': typeof LayoutAdminAdminsRoute
  '/_layout/admin/bar': typeof LayoutAdminBarRoute
  '/_layout/admin/beta': typeof LayoutAdminBetaRoute
  '/_layout/admin/broadcasts': typeof LayoutAdminBroadcastsRoute
  '/_layout/admin/firm-suggestions': typeof LayoutAdminFirmSuggestionsRoute
  '/_layout/admin/insights': typeof LayoutAdminInsightsRoute
  '/_layout/admin/opportunities': typeof LayoutAdminOpportunitiesRoute
  '/_layout/admin/vacancies': typeof LayoutAdminVacanciesRoute
  '/_layout/admin/waitlist': typeof LayoutAdminWaitlistRoute
  '/_layout/playbook/$slug': typeof LayoutPlaybookSlugRoute
  '/_layout/profile/edit': typeof LayoutProfileEditRoute
  '/_layout/the-bar/browse': typeof LayoutTheBarBrowseRoute
  '/_layout/the-bar/history': typeof LayoutTheBarHistoryRoute
  '/_layout/the-bar/leaderboard': typeof LayoutTheBarLeaderboardRoute
  '/_layout/the-bar/preview': typeof LayoutTheBarPreviewRoute
  '/_layout/tools/cv-analyser': typeof LayoutToolsCvAnalyserRoute
  '/_layout/u/$username': typeof LayoutUUsernameRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/directory/': typeof LayoutDirectoryIndexRoute
  '/_layout/playbook/': typeof LayoutPlaybookIndexRoute
  '/_layout/the-bar/': typeof LayoutTheBarIndexRoute
  '/_layout/tools/': typeof LayoutToolsIndexRoute
  '/_layout/directory/firm/$slug': typeof LayoutDirectoryFirmSlugRoute
  '/_layout/the-bar/challenge/$id': typeof LayoutTheBarChallengeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/choose-username'
    | '/reset-password'
    | '/unsubscribe'
    | '/admin'
    | '/app'
    | '/applications'
    | '/directory'
    | '/dock-lab'
    | '/opportunities'
    | '/opportunities-preview'
    | '/playbook'
    | '/resources'
    | '/the-bar'
    | '/tools'
    | '/tour-lab'
    | '/vacancies'
    | '/waitlist'
    | '/admin/login'
    | '/beta/round-2'
    | '/beta/'
    | '/admin/admins'
    | '/admin/bar'
    | '/admin/beta'
    | '/admin/broadcasts'
    | '/admin/firm-suggestions'
    | '/admin/insights'
    | '/admin/opportunities'
    | '/admin/vacancies'
    | '/admin/waitlist'
    | '/playbook/$slug'
    | '/profile/edit'
    | '/the-bar/browse'
    | '/the-bar/history'
    | '/the-bar/leaderboard'
    | '/the-bar/preview'
    | '/tools/cv-analyser'
    | '/u/$username'
    | '/admin/'
    | '/directory/'
    | '/playbook/'
    | '/the-bar/'
    | '/tools/'
    | '/directory/firm/$slug'
    | '/the-bar/challenge/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/choose-username'
    | '/reset-password'
    | '/unsubscribe'
    | '/app'
    | '/applications'
    | '/dock-lab'
    | '/opportunities'
    | '/opportunities-preview'
    | '/resources'
    | '/tour-lab'
    | '/vacancies'
    | '/waitlist'
    | '/admin/login'
    | '/beta/round-2'
    | '/'
    | '/beta'
    | '/admin/admins'
    | '/admin/bar'
    | '/admin/beta'
    | '/admin/broadcasts'
    | '/admin/firm-suggestions'
    | '/admin/insights'
    | '/admin/opportunities'
    | '/admin/vacancies'
    | '/admin/waitlist'
    | '/playbook/$slug'
    | '/profile/edit'
    | '/the-bar/browse'
    | '/the-bar/history'
    | '/the-bar/leaderboard'
    | '/the-bar/preview'
    | '/tools/cv-analyser'
    | '/u/$username'
    | '/admin'
    | '/directory'
    | '/playbook'
    | '/the-bar'
    | '/tools'
    | '/directory/firm/$slug'
    | '/the-bar/challenge/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/choose-username'
    | '/reset-password'
    | '/unsubscribe'
    | '/_layout/admin'
    | '/_layout/app'
    | '/_layout/applications'
    | '/_layout/directory'
    | '/_layout/dock-lab'
    | '/_layout/opportunities'
    | '/_layout/opportunities-preview'
    | '/_layout/playbook'
    | '/_layout/resources'
    | '/_layout/the-bar'
    | '/_layout/tools'
    | '/_layout/tour-lab'
    | '/_layout/vacancies'
    | '/_layout/waitlist'
    | '/admin/login'
    | '/beta/round-2'
    | '/_layout/'
    | '/beta/'
    | '/_layout/admin/admins'
    | '/_layout/admin/bar'
    | '/_layout/admin/beta'
    | '/_layout/admin/broadcasts'
    | '/_layout/admin/firm-suggestions'
    | '/_layout/admin/insights'
    | '/_layout/admin/opportunities'
    | '/_layout/admin/vacancies'
    | '/_layout/admin/waitlist'
    | '/_layout/playbook/$slug'
    | '/_layout/profile/edit'
    | '/_layout/the-bar/browse'
    | '/_layout/the-bar/history'
    | '/_layout/the-bar/leaderboard'
    | '/_layout/the-bar/preview'
    | '/_layout/tools/cv-analyser'
    | '/_layout/u/$username'
    | '/_layout/admin/'
    | '/_layout/directory/'
    | '/_layout/playbook/'
    | '/_layout/the-bar/'
    | '/_layout/tools/'
    | '/_layout/directory/firm/$slug'
    | '/_layout/the-bar/challenge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChooseUsernameRoute: typeof ChooseUsernameRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BetaRound2Route: typeof BetaRound2Route
  BetaIndexRoute: typeof BetaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-username': {
      id: '/choose-username'
      path: '/choose-username'
      fullPath: '/choose-username'
      preLoaderRoute: typeof ChooseUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta/': {
      id: '/beta/'
      path: '/beta'
      fullPath: '/beta/'
      preLoaderRoute: typeof BetaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/beta/round-2': {
      id: '/beta/round-2'
      path: '/beta/round-2'
      fullPath: '/beta/round-2'
      preLoaderRoute: typeof BetaRound2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/waitlist': {
      id: '/_layout/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof LayoutWaitlistRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vacancies': {
      id: '/_layout/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof LayoutVacanciesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tour-lab': {
      id: '/_layout/tour-lab'
      path: '/tour-lab'
      fullPath: '/tour-lab'
      preLoaderRoute: typeof LayoutTourLabRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools': {
      id: '/_layout/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof LayoutToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/the-bar': {
      id: '/_layout/the-bar'
      path: '/the-bar'
      fullPath: '/the-bar'
      preLoaderRoute: typeof LayoutTheBarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resources': {
      id: '/_layout/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof LayoutResourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playbook': {
      id: '/_layout/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof LayoutPlaybookRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/opportunities-preview': {
      id: '/_layout/opportunities-preview'
      path: '/opportunities-preview'
      fullPath: '/opportunities-preview'
      preLoaderRoute: typeof LayoutOpportunitiesPreviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/opportunities': {
      id: '/_layout/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof LayoutOpportunitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dock-lab': {
      id: '/_layout/dock-lab'
      path: '/dock-lab'
      fullPath: '/dock-lab'
      preLoaderRoute: typeof LayoutDockLabRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/directory': {
      id: '/_layout/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof LayoutDirectoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications': {
      id: '/_layout/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof LayoutApplicationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app': {
      id: '/_layout/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof LayoutAppRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools/': {
      id: '/_layout/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof LayoutToolsIndexRouteImport
      parentRoute: typeof LayoutToolsRoute
    }
    '/_layout/the-bar/': {
      id: '/_layout/the-bar/'
      path: '/'
      fullPath: '/the-bar/'
      preLoaderRoute: typeof LayoutTheBarIndexRouteImport
      parentRoute: typeof LayoutTheBarRoute
    }
    '/_layout/playbook/': {
      id: '/_layout/playbook/'
      path: '/'
      fullPath: '/playbook/'
      preLoaderRoute: typeof LayoutPlaybookIndexRouteImport
      parentRoute: typeof LayoutPlaybookRoute
    }
    '/_layout/directory/': {
      id: '/_layout/directory/'
      path: '/'
      fullPath: '/directory/'
      preLoaderRoute: typeof LayoutDirectoryIndexRouteImport
      parentRoute: typeof LayoutDirectoryRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/u/$username': {
      id: '/_layout/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof LayoutUUsernameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools/cv-analyser': {
      id: '/_layout/tools/cv-analyser'
      path: '/cv-analyser'
      fullPath: '/tools/cv-analyser'
      preLoaderRoute: typeof LayoutToolsCvAnalyserRouteImport
      parentRoute: typeof LayoutToolsRoute
    }
    '/_layout/the-bar/preview': {
      id: '/_layout/the-bar/preview'
      path: '/preview'
      fullPath: '/the-bar/preview'
      preLoaderRoute: typeof LayoutTheBarPreviewRouteImport
      parentRoute: typeof LayoutTheBarRoute
    }
    '/_layout/the-bar/leaderboard': {
      id: '/_layout/the-bar/leaderboard'
      path: '/leaderboard'
      fullPath: '/the-bar/leaderboard'
      preLoaderRoute: typeof LayoutTheBarLeaderboardRouteImport
      parentRoute: typeof LayoutTheBarRoute
    }
    '/_layout/the-bar/history': {
      id: '/_layout/the-bar/history'
      path: '/history'
      fullPath: '/the-bar/history'
      preLoaderRoute: typeof LayoutTheBarHistoryRouteImport
      parentRoute: typeof LayoutTheBarRoute
    }
    '/_layout/the-bar/browse': {
      id: '/_layout/the-bar/browse'
      path: '/browse'
      fullPath: '/the-bar/browse'
      preLoaderRoute: typeof LayoutTheBarBrowseRouteImport
      parentRoute: typeof LayoutTheBarRoute
    }
    '/_layout/profile/edit': {
      id: '/_layout/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof LayoutProfileEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playbook/$slug': {
      id: '/_layout/playbook/$slug'
      path: '/$slug'
      fullPath: '/playbook/$slug'
      preLoaderRoute: typeof LayoutPlaybookSlugRouteImport
      parentRoute: typeof LayoutPlaybookRoute
    }
    '/_layout/admin/waitlist': {
      id: '/_layout/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof LayoutAdminWaitlistRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/vacancies': {
      id: '/_layout/admin/vacancies'
      path: '/vacancies'
      fullPath: '/admin/vacancies'
      preLoaderRoute: typeof LayoutAdminVacanciesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/opportunities': {
      id: '/_layout/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof LayoutAdminOpportunitiesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/insights': {
      id: '/_layout/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof LayoutAdminInsightsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/firm-suggestions': {
      id: '/_layout/admin/firm-suggestions'
      path: '/firm-suggestions'
      fullPath: '/admin/firm-suggestions'
      preLoaderRoute: typeof LayoutAdminFirmSuggestionsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/broadcasts': {
      id: '/_layout/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof LayoutAdminBroadcastsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/beta': {
      id: '/_layout/admin/beta'
      path: '/beta'
      fullPath: '/admin/beta'
      preLoaderRoute: typeof LayoutAdminBetaRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/bar': {
      id: '/_layout/admin/bar'
      path: '/bar'
      fullPath: '/admin/bar'
      preLoaderRoute: typeof LayoutAdminBarRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/admins': {
      id: '/_layout/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof LayoutAdminAdminsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/the-bar/challenge/$id': {
      id: '/_layout/the-bar/challenge/$id'
      path: '/challenge/$id'
      fullPath: '/the-bar/challenge/$id'
      preLoaderRoute: typeof LayoutTheBarChallengeIdRouteImport
      parentRoute: typeof LayoutTheBarRoute
    }
    '/_layout/directory/firm/$slug': {
      id: '/_layout/directory/firm/$slug'
      path: '/firm/$slug'
      fullPath: '/directory/firm/$slug'
      preLoaderRoute: typeof LayoutDirectoryFirmSlugRouteImport
      parentRoute: typeof LayoutDirectoryRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAdminsRoute: typeof LayoutAdminAdminsRoute
  LayoutAdminBarRoute: typeof LayoutAdminBarRoute
  LayoutAdminBetaRoute: typeof LayoutAdminBetaRoute
  LayoutAdminBroadcastsRoute: typeof LayoutAdminBroadcastsRoute
  LayoutAdminFirmSuggestionsRoute: typeof LayoutAdminFirmSuggestionsRoute
  LayoutAdminInsightsRoute: typeof LayoutAdminInsightsRoute
  LayoutAdminOpportunitiesRoute: typeof LayoutAdminOpportunitiesRoute
  LayoutAdminVacanciesRoute: typeof LayoutAdminVacanciesRoute
  LayoutAdminWaitlistRoute: typeof LayoutAdminWaitlistRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAdminsRoute: LayoutAdminAdminsRoute,
  LayoutAdminBarRoute: LayoutAdminBarRoute,
  LayoutAdminBetaRoute: LayoutAdminBetaRoute,
  LayoutAdminBroadcastsRoute: LayoutAdminBroadcastsRoute,
  LayoutAdminFirmSuggestionsRoute: LayoutAdminFirmSuggestionsRoute,
  LayoutAdminInsightsRoute: LayoutAdminInsightsRoute,
  LayoutAdminOpportunitiesRoute: LayoutAdminOpportunitiesRoute,
  LayoutAdminVacanciesRoute: LayoutAdminVacanciesRoute,
  LayoutAdminWaitlistRoute: LayoutAdminWaitlistRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutDirectoryRouteChildren {
  LayoutDirectoryIndexRoute: typeof LayoutDirectoryIndexRoute
  LayoutDirectoryFirmSlugRoute: typeof LayoutDirectoryFirmSlugRoute
}

const LayoutDirectoryRouteChildren: LayoutDirectoryRouteChildren = {
  LayoutDirectoryIndexRoute: LayoutDirectoryIndexRoute,
  LayoutDirectoryFirmSlugRoute: LayoutDirectoryFirmSlugRoute,
}

const LayoutDirectoryRouteWithChildren = LayoutDirectoryRoute._addFileChildren(
  LayoutDirectoryRouteChildren,
)

interface LayoutPlaybookRouteChildren {
  LayoutPlaybookSlugRoute: typeof LayoutPlaybookSlugRoute
  LayoutPlaybookIndexRoute: typeof LayoutPlaybookIndexRoute
}

const LayoutPlaybookRouteChildren: LayoutPlaybookRouteChildren = {
  LayoutPlaybookSlugRoute: LayoutPlaybookSlugRoute,
  LayoutPlaybookIndexRoute: LayoutPlaybookIndexRoute,
}

const LayoutPlaybookRouteWithChildren = LayoutPlaybookRoute._addFileChildren(
  LayoutPlaybookRouteChildren,
)

interface LayoutTheBarRouteChildren {
  LayoutTheBarBrowseRoute: typeof LayoutTheBarBrowseRoute
  LayoutTheBarHistoryRoute: typeof LayoutTheBarHistoryRoute
  LayoutTheBarLeaderboardRoute: typeof LayoutTheBarLeaderboardRoute
  LayoutTheBarPreviewRoute: typeof LayoutTheBarPreviewRoute
  LayoutTheBarIndexRoute: typeof LayoutTheBarIndexRoute
  LayoutTheBarChallengeIdRoute: typeof LayoutTheBarChallengeIdRoute
}

const LayoutTheBarRouteChildren: LayoutTheBarRouteChildren = {
  LayoutTheBarBrowseRoute: LayoutTheBarBrowseRoute,
  LayoutTheBarHistoryRoute: LayoutTheBarHistoryRoute,
  LayoutTheBarLeaderboardRoute: LayoutTheBarLeaderboardRoute,
  LayoutTheBarPreviewRoute: LayoutTheBarPreviewRoute,
  LayoutTheBarIndexRoute: LayoutTheBarIndexRoute,
  LayoutTheBarChallengeIdRoute: LayoutTheBarChallengeIdRoute,
}

const LayoutTheBarRouteWithChildren = LayoutTheBarRoute._addFileChildren(
  LayoutTheBarRouteChildren,
)

interface LayoutToolsRouteChildren {
  LayoutToolsCvAnalyserRoute: typeof LayoutToolsCvAnalyserRoute
  LayoutToolsIndexRoute: typeof LayoutToolsIndexRoute
}

const LayoutToolsRouteChildren: LayoutToolsRouteChildren = {
  LayoutToolsCvAnalyserRoute: LayoutToolsCvAnalyserRoute,
  LayoutToolsIndexRoute: LayoutToolsIndexRoute,
}

const LayoutToolsRouteWithChildren = LayoutToolsRoute._addFileChildren(
  LayoutToolsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAppRoute: typeof LayoutAppRoute
  LayoutApplicationsRoute: typeof LayoutApplicationsRoute
  LayoutDirectoryRoute: typeof LayoutDirectoryRouteWithChildren
  LayoutDockLabRoute: typeof LayoutDockLabRoute
  LayoutOpportunitiesRoute: typeof LayoutOpportunitiesRoute
  LayoutOpportunitiesPreviewRoute: typeof LayoutOpportunitiesPreviewRoute
  LayoutPlaybookRoute: typeof LayoutPlaybookRouteWithChildren
  LayoutResourcesRoute: typeof LayoutResourcesRoute
  LayoutTheBarRoute: typeof LayoutTheBarRouteWithChildren
  LayoutToolsRoute: typeof LayoutToolsRouteWithChildren
  LayoutTourLabRoute: typeof LayoutTourLabRoute
  LayoutVacanciesRoute: typeof LayoutVacanciesRoute
  LayoutWaitlistRoute: typeof LayoutWaitlistRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileEditRoute: typeof LayoutProfileEditRoute
  LayoutUUsernameRoute: typeof LayoutUUsernameRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAppRoute: LayoutAppRoute,
  LayoutApplicationsRoute: LayoutApplicationsRoute,
  LayoutDirectoryRoute: LayoutDirectoryRouteWithChildren,
  LayoutDockLabRoute: LayoutDockLabRoute,
  LayoutOpportunitiesRoute: LayoutOpportunitiesRoute,
  LayoutOpportunitiesPreviewRoute: LayoutOpportunitiesPreviewRoute,
  LayoutPlaybookRoute: LayoutPlaybookRouteWithChildren,
  LayoutResourcesRoute: LayoutResourcesRoute,
  LayoutTheBarRoute: LayoutTheBarRouteWithChildren,
  LayoutToolsRoute: LayoutToolsRouteWithChildren,
  LayoutTourLabRoute: LayoutTourLabRoute,
  LayoutVacanciesRoute: LayoutVacanciesRoute,
  LayoutWaitlistRoute: LayoutWaitlistRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileEditRoute: LayoutProfileEditRoute,
  LayoutUUsernameRoute: LayoutUUsernameRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
  ChooseUsernameRoute: ChooseUsernameRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminLoginRoute: AdminLoginRoute,
  BetaRound2Route: BetaRound2Route,
  BetaIndexRoute: BetaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
