// This file is auto-generated by the TanStack Router Vite plugin at build time.
// Do not edit manually. The placeholder below allows the project to typecheck
// before the plugin generates the real route tree.
export const routeTree: any = {} as any;
